import { create } from '@stylexjs/stylex';
import {
  colorVars as c,
  spacingVars as s,
  radiusVars as r,
  borderVars as b,
  typographyVars as t,
} from '@astryxdesign/core/theme/tokens.stylex';

export const ui = create({
  app: {
    minHeight: '100dvh',
    backgroundColor: c['--color-background-body'],
    color: c['--color-text-primary'],
    display: 'grid',
    gridTemplateColumns: {
      default: '14rem minmax(0,1fr)',
      '@media (max-width: 800px)': 'minmax(0,1fr)',
    },
  },
  sidebar: {
    padding: s['--spacing-4'],
    display: 'flex',
    flexDirection: 'column',
    gap: s['--spacing-6'],
    borderRightWidth: b['--border-width'],
    borderRightStyle: 'solid',
    borderRightColor: c['--color-border'],
    position: { default: 'sticky', '@media (max-width: 800px)': 'relative' },
    top: 0,
    height: { default: '100dvh', '@media (max-width: 800px)': 'auto' },
    backgroundColor: c['--color-background-surface'],
  },
  nav: {
    display: 'flex',
    flexDirection: { default: 'column', '@media (max-width: 800px)': 'row' },
    gap: s['--spacing-1'],
    flexWrap: 'wrap',
  },
  navButton: {
    justifyContent: 'flex-start',
    width: { default: '100%', '@media (max-width: 800px)': 'auto' },
  },
  themeButton: { marginTop: { default: 'auto', '@media (max-width: 800px)': 0 } },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: s['--spacing-3'],
    padding: s['--spacing-4'],
    borderBottomWidth: b['--border-width'],
    borderBottomStyle: 'solid',
    borderBottomColor: c['--color-border'],
    backgroundColor: c['--color-background-surface'],
  },
  page: {
    padding: { default: s['--spacing-6'], '@media (max-width: 640px)': s['--spacing-3'] },
    width: '100%',
    maxWidth: '96rem',
    marginInline: 'auto',
    minWidth: 0,
  },
  stack: { display: 'flex', flexDirection: 'column', gap: s['--spacing-4'], minWidth: 0 },
  tight: { display: 'flex', flexDirection: 'column', gap: s['--spacing-2'], minWidth: 0 },
  row: {
    display: 'flex',
    alignItems: 'center',
    gap: s['--spacing-3'],
    minWidth: 0,
    flexWrap: 'wrap',
  },
  between: { justifyContent: 'space-between' },
  end: { justifyContent: 'flex-end' },
  grow: { flex: 1, minWidth: 0 },
  panel: {
    borderWidth: b['--border-width'],
    borderStyle: 'solid',
    borderColor: c['--color-border'],
    borderRadius: r['--radius-container'],
    backgroundColor: c['--color-background-surface'],
    minWidth: 0,
    overflow: 'hidden',
  },
  padding: { padding: s['--spacing-4'] },
  divider: {
    borderTopWidth: b['--border-width'],
    borderTopStyle: 'solid',
    borderTopColor: c['--color-border'],
  },
  grid: {
    display: 'grid',
    gap: s['--spacing-4'],
    gridTemplateColumns: {
      default: 'repeat(2,minmax(0,1fr))',
      '@media (max-width: 640px)': 'minmax(0,1fr)',
    },
    minWidth: 0,
  },
  fields: {
    display: 'grid',
    gap: s['--spacing-4'],
    gridTemplateColumns: 'repeat(2,minmax(0,1fr))',
    minWidth: 0,
  },
  workbench: {
    display: 'grid',
    gap: s['--spacing-5'],
    gridTemplateColumns: {
      default: 'minmax(0,1fr) 23rem',
      '@media (max-width: 1100px)': 'minmax(0,1fr)',
    },
    alignItems: 'start',
    minWidth: 0,
  },
  audit: {
    display: 'grid',
    gap: s['--spacing-5'],
    gridTemplateColumns: {
      default: '19rem minmax(0,1fr)',
      '@media (max-width: 1000px)': 'minmax(0,1fr)',
    },
    alignItems: 'start',
    minWidth: 0,
  },
  auditList: {
    maxHeight: { default: 'calc(100dvh - 12rem)', '@media (max-width: 1000px)': '18rem' },
    overflowY: 'auto',
    padding: s['--spacing-2'],
    display: 'flex',
    flexDirection: 'column',
    gap: s['--spacing-1'],
  },
  auditRow: {
    height: 'auto',
    padding: s['--spacing-3'],
    justifyContent: 'flex-start',
    textAlign: 'start',
    width: '100%',
    whiteSpace: 'normal',
  },
  image: { width: '100%', height: 'auto', display: 'block', objectFit: 'contain' },
  preview: {
    aspectRatio: '16 / 9',
    display: 'grid',
    placeItems: 'center',
    overflow: 'hidden',
    backgroundColor: c['--color-background-muted'],
    borderRadius: r['--radius-element'],
    borderWidth: b['--border-width'],
    borderStyle: 'solid',
    borderColor: c['--color-border'],
    minWidth: 0,
  },
  previewEmpty: { aspectRatio: 'auto', minHeight: { default: 360, '@media (max-width: 640px)': 280 } },
  previewImage: { width: '100%', height: '100%', objectFit: 'contain' },
  placeholder: {
    textAlign: 'center',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: s['--spacing-3'],
    padding: s['--spacing-5'],
    minWidth: 0,
  },
  empty: { minHeight: '18rem' },
  metrics: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit,minmax(6rem,1fr))',
    gap: s['--spacing-4'],
  },
  muted: { color: c['--color-text-secondary'] },
  wrap: { overflowWrap: 'anywhere', minWidth: 0 },
  scroll: { maxHeight: '20rem', overflowY: 'auto', minWidth: 0 },
  code: {
    whiteSpace: 'pre-wrap',
    overflowWrap: 'anywhere',
    maxHeight: '14rem',
    overflowY: 'auto',
    fontFamily: t['--font-family-code'],
    backgroundColor: c['--color-background-muted'],
    padding: s['--spacing-3'],
    borderRadius: r['--radius-element'],
  },
  thumb: {
    width: s['--spacing-10'],
    height: s['--spacing-10'],
    objectFit: 'cover',
    borderRadius: r['--radius-inner'],
  },
  selected: { borderColor: c['--color-success'] },
  dialog: { textAlign: 'start', maxWidth: '100%' },
  link: { color: c['--color-text-accent'], textDecoration: 'underline', overflowWrap: 'anywhere' },
});
